/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    docs: [
        {
            type: 'doc',
            id: 'index',
            label: 'Home'
        },
        {
            type: 'category',
            label: 'Getting Started',
            items: [
                {
                    type: 'category',
                            label: 'Install Open Libra CLI',
                            items: [
                                'getting-started/install-open-libra-cli/install-open-libra-cli',
                                'getting-started/install-open-libra-cli/install-open-libra-cli-binaries',
                            ]
                },
                'getting-started/install-wallet',
            ],
        },
        {
            type: 'category',
            label: 'Guides',
            items: [
                {
                    type: 'category',
                    label: 'Node Operators',
                    items: [
                        'guides/node-operators/validators/validator-quickstart',
                        'guides/node-operators/validators/detailed-instructions',

                        'guides/node-operators/validators/governance-tx',
                        'guides/node-operators/validators/hot-upgrades',
                        'guides/node-operators/validators/network-health',
                        'guides/node-operators/validators/register',
                        'guides/node-operators/validators/rescue',
                        'guides/node-operators/validators/sybil-resistance',
                        'guides/node-operators/validators/vfn-setup',
                        'guides/node-operators/validators/with-docker-setup',
                        'guides/node-operators/validators/network-architecture',
                        {
                            type: 'category',
                            label: 'YAML templates',
                            items: [
                                {
                                    type: 'autogenerated',
                                    dirName: 'guides/node-operators/validators/yaml-templates',
                                },
                            ],
                        },
                    ],
                },
                {
                    type: 'category',
                    label: 'Developers',
                    items: [
                        'guides/developers/dev-quick-start',
                        'guides/developers/formal-verification',
                        'guides/developers/governance-fixtures',
                        'guides/developers/smoke-tests',
                        'guides/developers/technology',
                        'guides/developers/testnet-deploy',
                        {
                            type: 'category',
                            label: 'Move',
                            items: [
                                'guides/developers/move/move-smart-contracts',
                                'guides/developers/move/move-coding-conventions',
                                'guides/developers/move/move-data-initialization',
                            ],
                        },
                    ],
                },
                {
                    type: 'category',
                    label: 'Community Wallet Operators',
                    items: [
                        'guides/community-wallet-ops/community-wallet-activation',
                        'guides/community-wallet-ops/reauthorize-in-v8',
                        'guides/community-wallet-ops/setup-multisig',
                        'guides/community-wallet-ops/send-coins',
                    ],
                },
                {
                    type: 'category',
                    label: 'Integrations',
                    items: [
                        'guides/integrations/exchanges',
                        'guides/integrations/integrators',
                        // 'guides/integrations/oracles',
                        // 'guides/integrations/applications'
                    ],
                }
            ],
        },
        {
            type: 'category',
            label: 'CLI & API References',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'references/tools',
                },
            ],
        },
        {
            type: 'category',
            label: 'Concepts',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'concepts/community',
                },
                {
                    type: 'category',
                    label: 'Community Wallet Programs',
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'concepts/community-programs',
                        },
                    ],
                },
            ],
        },
        'faq/faq',
        'glossary/glossary',
        {
            type: 'link',
            label: 'Blog',
            href: '/blog',
        }
    ],
};

module.exports = sidebars;
