name: Test deployment

on:
  push:
    branches: ["*"]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Test build website
        run: bun run build
